apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
  - namespace.yaml

helmCharts:
  - name: minio
    repo: https://charts.min.io/
    version: 5.3.0
    releaseName: minio
    namespace: minio
    valuesFile: values.yaml
