apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-storage
  namespace: authelia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: authelia
data:
  users_database.yml: |
    users:
      admin:
        displayname: "Admin User"
        password: "$argon2id$v=19$m=65536,t=3,p=4$vmI3odHrLTpaMFazHAElSw$m6Iro6Q+S4fIkvIzAOUGgVANvRrkwclH83jEK3wciZU"
        email: admin@home.mcztest.com
        groups:
          - admins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
      - name: authelia
        image: authelia/authelia:latest
        ports:
        - containerPort: 9091
        env:
        - name: AUTHELIA_JWT_SECRET_FILE
          value: /secrets/jwt_secret
        - name: AUTHELIA_SESSION_SECRET_FILE
          value: /secrets/session_secret
        - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
          value: /secrets/storage_encryption_key
        - name: AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
          value: /secrets/smtp/smtp-password
        volumeMounts:
        - name: config
          mountPath: /config/configuration.yml
          subPath: configuration.yml
          readOnly: true
        - name: users
          mountPath: /config/users_database.yml
          subPath: users_database.yml
          readOnly: true
        - name: secrets
          mountPath: /secrets
          readOnly: true
        - name: smtp-secret
          mountPath: /secrets/smtp
          readOnly: true
        - name: storage
          mountPath: /config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: config
        configMap:
          name: authelia-config
      - name: users
        configMap:
          name: authelia-users
      - name: secrets
        secret:
          secretName: authelia-secrets
      - name: smtp-secret
        secret:
          secretName: authelia-smtp
      - name: storage
        persistentVolumeClaim:
          claimName: authelia-storage
---
apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: authelia
spec:
  selector:
    app: authelia
  ports:
  - port: 80
    targetPort: 9091
