apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - namespace.yaml
  - redis.yaml
  - config.yaml
  - authelia.yaml
  - sealed-secrets.yaml
  - ingress.yaml
