---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-smtp
  namespace: authelia
spec:
  encryptedData:
    smtp-password: AgBhoH0HZp+ditXgwkL44gJLEQSyd0BHykd6HJ68mbA61DyExwLCO05tuL1zdzOk4UQn1NR0pIA5h1DCmNFxgHVSAsPIqQAaqZZK67LbXIdGmuL0j4EAeHa3MhsK87l1c3Yno29Lh3LNzipLuegOMIzJ/YTKjzTfanAsmJDNNX7aias8CuDEO7aAMcMl3vsO1tXSYiUGIgwxMA7eravzrg2juFuMlHehAuji44f4aa8GppAe7cDChBcjst3PDdcVUnSleDrTaaIKJ26pZvAykRxr19W5s1d032g/M+/DZYwhgMkzeta4GX0ypAKugZb4WULbgWM3t0hawCjcsTTMVpaqL8+PBp2uEgNJLR+aWrA9ctnQ5V/e0QSjG2rKSZ2k+H/KH+2M9FpPxtxkrwE3u7vz/X1iv84alpVtUZXI+j3/PcYvxCeBYL1zWwKUf7kqg5S2+Bua7ZSZr9kGwv7ylb2Dr90FORPlR+ebSkJIQ2sdmUfTh8rJP9ksTJvmh3ZX1eKTNt8AK62i3hIJiVtnO8utoq+0fHnLu9AorhM7hOIEfc4vu3QBlE8ve3ga8YyuZudx4cMGupLEPgxlxtqxdPk6uWzVI6IBslGsHXIwbcmNHOeOLVrVOe6Ugo6NBAYRl0NcawUGie7+a3OnecnjXsplmUEXuxsPxtlOHbc0KFxDs72xWWEnfm88VDPCJKZn340uL40lucJGywbXcKmnUfmB
  template:
    metadata:
      name: authelia-smtp
      namespace: authelia
    type: Opaque
