---
# MetalLB IP Address Pool
# This defines the range of IPs that MetalLB can assign to LoadBalancer services
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.200.100-192.168.200.110  # 10 IPs available for LoadBalancer services
---
# L2 Advertisement
# Announces the LoadBalancer IPs on the local network using Layer 2 (ARP)
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool
