---
apiVersion: v1
kind: Service
metadata:
  name: superset-postgres
  namespace: superset
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: superset-postgres
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-postgres-pvc
  namespace: superset
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-postgres
  namespace: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset-postgres
  template:
    metadata:
      labels:
        app: superset-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_DB
          value: superset
        - name: POSTGRES_USER
          value: superset
        - name: POSTGRES_PASSWORD
          value: superset
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: superset-postgres-pvc
