---
apiVersion: v1
kind: Service
metadata:
  name: superset-redis
  namespace: superset
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: superset-redis
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: superset-redis-headless
  namespace: superset
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: superset-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-redis-pvc
  namespace: superset
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-redis
  namespace: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset-redis
  template:
    metadata:
      labels:
        app: superset-redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        command:
        - redis-server
        - --appendonly
        - "yes"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 250m
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: superset-redis-pvc
