apiVersion: v1
kind: Service
metadata:
  name: pihole-external
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pihole-external
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.200.62
    ports:
      - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /admin/$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - pihole.home.mcztest.com
    secretName: pihole-tls
  rules:
  - host: pihole.home.mcztest.com
    http:
      paths:
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: pihole-external
            port:
              number: 80
