---
# CA Issuer
# This issuer uses the homelab CA to sign certificates for ingress resources
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-ca-issuer
spec:
  ca:
    secretName: homelab-ca-secret
