# ArgoCD Application for platform services
# Manages: Gitea, Gitea Actions, Monitoring (Prometheus/Grafana), Registry, VM Proxies
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    homelab.mcztest.com/type: platform
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea:3000/homelab/proxmox.git
    targetRevision: HEAD
    path: cluster/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
